#!/usr/bin/php
<?php

require 'vendor/autoload.php';

use GuzzleHttp\Client;
use function Downloader\Downloader\downloadPage;

if (empty($argv[1])) {
    exit('Empty arguments');
}

switch ($argv[1]) {
    case '-h':
    case '--help':
        exit("
Downloads page from URL and save it locally 

Usage:                                                                                                   
    page-loader (-h|--help)                                                                              
    page-loader [(-o|--output) <dir>] <url>                                                                   
    page-loader (-v|--version)                                                                           
                                                                                                         
Options:                                                                                                 
  -h --help            display help for command                                                          
  -v --version         output the version number                                                         
  -o --output <dir>    output dir [default: current directory]
  ");
    case '-v':
    case '--version':
        exit('page-loader v1.0.0');
    case '-o':
    case '--output':
        $url = !empty($argv[3]) ? $argv[3] : (!empty($argv[2]) ? $argv[2] : '');
        $uploadDir = !empty($argv[3]) ? $argv[2] : null;
        try {
            $result = downloadPage($url, $uploadDir, new Client());
            exit($result);
        } catch (\Exception $e) {
            exit($e->getMessage());
        }
    default:
        exit('Unknown arguments');
}